name: ev_charger_finder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.2
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  url_launcher: ^6.3.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/map_styles/
    - assets/icon/

# --- NEW: Configuration for flutter_launcher_icons (Simplified) ---
flutter_launcher_icons:
  android: true
  ios: false
  
  # Path to your high-resolution app icon
  image_path: "assets/icon/app_icon.png"

  # (Optional) For Android 8.0+ adaptive icons
  # You can specify a background color or image for the icon's "safe area"
  adaptive_icon_background: "#FFFFFF" # Example: white background

  # The adaptive_icon_foreground line has been removed.
  # The tool will now use the main image_path for the foreground.

  min_sdk_android: 23